### ISSUE TITLE
Error while making the doc

### ISSUE THREAD

**Issue by Bertbk** [michal-h21/tex4ht-doc#2]
I tried to compile the doc on my computer but the compilation fail to build the `html` file

```
Output written on tex4ht_process.dvi (2 pages, 15888 bytes).
Transcript written on tex4ht_process.log.
dvisvgm -c 1.5 --exact --font-format=woff,ah tex4ht_process.dvi
pre-processing DVI file (format version 2)
processing page 1
  graphic size: 527.504752pt x 149.292204pt (185.396717mm x 52.470209mm)
  output written to tex4ht_process-1.svg
1 of 2 pages converted in 0.306787 seconds
make[1]: Leaving directory '/home/bertrand/src/tex4ht-doc/images/tex4ht_process'
make4ht -usm draft -c config -l -d out -f html5+common_domfilters -e build.mk4  tex4ht-doc.tex
[STATUS]  make4ht: Conversion started
[STATUS]  make4ht: Input file: tex4ht-doc.tex
...ve/texmf-dist/scripts/make4ht/make4ht-errorlogparser.lua:5: attempt to index a nil value (local 'filename')
make: *** [Makefile:31: tex4ht-doc.html] Error 1
```

Have you an idea?

Some info about my config:

- Debian 11
- make4ht version v0.3b
- Lualatex Version 1.10.0 (TeX Live 2019/Debian) 

Thanks!

PS : readme file is not displayed as (parsed) markdown on Github, maybe it should be renamed README.md?

**Comment by michal-h21** [comment]
Could you please try to run 

     make4ht -a  debug -usm draft -c config -l -d out -f html5+common_domfilters -e build.mk4  tex4ht-doc.tex

Current `make4ht` version is `0.3c` but it shouldn't produce such error. It may be caused by a older version of some packages. The previous command will produce full output to the terminal, so it should be more obvious where is the problem.

**Comment by Bertbk** [comment]
I get a LaTex error:

```
! LaTeX Error: File `images/tex4ht_process/tex4ht_process' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.102 ...idth]{images/tex4ht_process/tex4ht_process}
```

If I skip it, it works (it builds a .html doc file)

**Comment by michal-h21** [comment]
Does file `images/tex4ht_process/tex4ht_process.svg` exist? I think this may be caused by the error with the Graphics package that I fixed few months  ago. Maybe the fix is not included in Debian yet.

**Comment by Bertbk** [comment]
> Does file images/tex4ht_process/tex4ht_process.svg exist? 

~~No, it doesn't.~~ My bad ! There is a file `tex4ht_process-1.svg`! and it's viewable.

**Comment by michal-h21** [comment]
Ah I can reproduce the error now. The issue was the SVG filename, it really should be `tex4ht_process.svg`!. It should be fixed now.

**Comment by Bertbk** [comment]
Yes, it works now. Thank you!

**Comment by Bertbk** [comment]
Well, using `make` build a `html` file but it's almost empty:

```html
<!DOCTYPE html> 
<html lang="en-US" xml:lang="en-US" > 
<head> <title></title> 
<meta  charset="utf-8" /> 
<meta name="generator" content="TeX4ht (http://www.tug.org/tex4ht/)" /> 
<meta name="viewport" content="width=device-width,initial-scale=1" /> 
<link rel="stylesheet" type="text/css" href="tex4ht-doc.css" /> 
<meta name="src" content="tex4ht-doc.tex" /> 
<link rel="stylesheet" type="text/css" href="style.css" /> 
</head><body>
<div class="maketitle">
<h2 class="titleHead">TeX4ht Documentation</h2>
 <div class="author" ><span 
class="rm-lmr-12">by TeX4ht Project</span></div><br />
<div class="date" ><span 
class="rm-lmr-12">December 10, 2019</span></div>
</div>
</main> 
</body> 
</html>
```

Using the command you send me before (`make4ht -a  debug -usm draft -c config -l -d out -f html5+common_domfilters -e build.mk4  tex4ht-doc.tex`) leads to the good html file (without error)

**Comment by michal-h21** [comment]
The `make` command runs only one LaTeX compilation run by default, in order to achieve faster compilation. As temporary files usually exist, it doesn't do any harm. But it can cause troubles when you make a clean compilation, as there is no information about table of contents. 

You can run `make final` to force a full compilation. It should produce all necessary temporary files  and create a correct document.
