### ISSUE TITLE
typo argumens -> arguments

### ISSUE THREAD

**Issue by cedounet** [michal-h21/tex4ht-doc#3]
Hello, 

this is related to 
https://github.com/michal-h21/make4ht/pull/147 

in [sections/tex4ht-development.tex](https://github.com/michal-h21/tex4ht-doc/blob/04ac9be959fbc8c2c909ab2832a95070850b1eec/sections/tex4ht-development.tex#L151)

\DocCommand{NewConfigure}\marg{name}\oarg{number or parameters}\marg{code}
Variant of \cmd{NewConfigure} that doesn't define hooks with 
alphabetic prefixes, but it passes **_argumens_** of \cmd{Configure}
as \TeX\ arguments. See this exampe:
\begin{texsource}

**Comment by michal-h21** [comment]
You are right! I don't know why I produce so many typos for this word :)

Anyway, it should be fixed now.

**Comment by cedounet** [comment]
Is it ? That one is in the doc… another repo and I am not seeing the commit.

I can do a PR as well of course :)

**Comment by michal-h21** [comment]
It should be here: 664bc4464ae80a1e1ea37fbd4c67ed8014873178

But I am sure there will be much more issues in the documentation. It is sometimes chaotic and lot of stuff is missing - in particular part of the tutorial and developer info, also a lot of information about basic configurations.

**Comment by cedounet** [comment]
it is indeed... not sure why but didn't see it yesterday.
